### ISSUE TITLE
Error when loading utf-8 schema 

### ISSUE THREAD

**Issue by pajachiet** [AntoineAugusti/table-schema-to-markdown#4]
I got a weird `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 94: ordinal not in range(128)` error when converting a schema from PyCharm. (Weird because it does not happen when I run my script from the terminal)

It can be solved by adding `encoding='utf-8'` when loading json file.

> def convert_source(source, out_fd):
>     log.info("Loading schema from %r", source)
>     schema = json.load(open(source, encoding='utf-8'))

This is what is done by `retrieve_descriptor` in [tableschema-py](https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/helpers.py#L21). One solution could be to directly use this helper function to load the schema.

**Comment by AntoineAugusti** [comment]
Which Python version are you using?

**Comment by pajachiet** [comment]
Python 3.6.5

**Comment by AntoineAugusti** [comment]
According to https://docs.python.org/3/library/functions.html#open
> In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding

I've resorted to utf-8 by default.

**Comment by AntoineAugusti** [comment]
You can upgrade to v0.2.1 to have this fix

**Comment by pajachiet** [comment]
Great ! it works perfectly
